### ISSUE TITLE
Each web page should have a unique title

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#344] opened 2023-01-19 15:34 UTC
### Description

We currently seem to use the same title for all our web pages:  FlowForge | Run Node-RED in Production.  For SEO, we should be using unique titles that are more descriptive of the page.

**Comment by knolleary** [comment] 2023-01-19 15:55
Duplicate of #337 from a couple days ago - don't mind which issue we use to track... but we only need one

**Comment by iskerrett** [comment] 2023-01-19 16:02
I will delete this one and add my comments to the other one.

**Closed** 2023-01-19 16:03 UTC
Labels: task
