### ISSUE TITLE
Invisible Video on Homepage

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#347] opened 2023-01-19 22:16 UTC
### Current Behavior

<img width="999" alt="Screenshot 2023-01-19 at 22 14 48" src="https://user-images.githubusercontent.com/99246719/213574332-52f04e10-8b2f-4ab9-b341-3e628e879d2a.png">

Works fine locally, but visiting https://flowforge.com - it doesn't load for me, not able to see any errors either, very strange. First noticed it in the Session Recordings of our visitors, but just assumed it was our PostHog handled media.

After a while, it did load, but we should consider a better background/placeholder that is lighter to load?

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment] 2023-01-19 22:52
Maybe check network tab for any slow loading external resource - that wouldnt surface as an error.

**Comment by Pezmc** [comment] 2023-02-07 15:15
How it looks with relatively fast internet, the flash appears to be the youtube iframe loading in. We could workaround this by using an image that's swapped for the iframe on click, or as a deferred action that happens _after_ the page load. 

Additionally, note jumping as you resize the window. 

![2023-02-07 16 10 01](https://user-images.githubusercontent.com/507155/217283961-218597bb-8bf7-4985-b00a-de4bf0498f8a.gif)

**Comment by knolleary** [comment] 2023-03-16 19:04
I think this has been addressed by all the work done on optimising the website. I can't reproduce any glitches on the video.

**Closed by knolleary** 2023-03-16 19:04 UTC
Labels: bug, priority:medium

**Comment by Pezmc** [comment] 2023-03-17 12:41
Fixed in https://github.com/flowforge/website/issues/347
