### ISSUE TITLE
Reduce how long the page is blocked from responding to user input

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/website#427] opened 2023-02-17 15:09 UTC
### Epic

426

### Description

**As a:** Website visitor

**I want to:** not be blocked by JS to input data

**So that:** I can move on with what I'd like to do

### Acceptance Criteria

- [ ] All effected pages on: https://app-eu1.hubspot.com/content-strategy/26586079/recommendations/domain/16160539/hostname/16711611/category/PERFORMANCE/type/REDUCE_TOTAL_BLOCKING_TIME report no issue

**Comment by Pezmc** [comment] 2023-02-22 09:40
Effectively a duplicate of #433, ironically, HubSpot is one of the main causes of page load delay.

**Comment by Pezmc** [comment] 2023-03-08 12:06
Solved as much as possible as part of #401, times are significantly reduced across the board, but not below HubSpot's (somewhat arbitrary) threshold of 200ms.
<img width="637" alt="Screenshot 2023-03-08 at 13 06 09" src="https://user-images.githubusercontent.com/507155/223709202-1d4aa7d0-8182-48ef-a3ee-0e5eeaf19a82.png">

**Closed by Pezmc** 2023-03-08 12:06 UTC
Labels: story
