### ISSUE TITLE
Update About FlowForge page

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#798] opened 2023-05-31 13:15 UTC
### Description

The About FlowForge page is out of date. I would like to suggest we rewrite to focus on the FlowForge story.  

Key topics should include:
- How FlowForge got created.
- Mission of FlowForge
- Updated company values
- Investors
- Team
- Careers / Jobs

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment] 2023-05-31 13:16
Duplicate of https://github.com/flowforge/website/issues/267 will close https://github.com/flowforge/website/issues/267 and direct efforts here.

**Comment by iskerrett** [comment] 2023-07-07 18:06
I have drafted the updated content for the About Us page.

https://docs.google.com/document/d/1HZheNoYn8hkJfABFfmM4xGMF1YjVDDpDuRj9ytkJmy0/edit?usp=sharing

**Comment by Yndira-FlowForge** [comment] 2023-07-19 14:29
Hi @iskerrett This is how it would look with the updated content, keeping the current structure of the page

![About Us](https://github.com/flowforge/website/assets/129537638/d6668450-ff2d-40a5-91e8-c20a0b5ca4bc)

[Here's the figma file](https://www.figma.com/file/hXDN5PnY3TmeQSv3n7Hna5/FlowForge-Website?type=design&node-id=2399%3A14441&mode=design&t=gvgmaQhymaKwvPb6-1)

I think the text for the first two sections is too long, and I don't like having such long text center-aligned, as it makes them harder to read. Maybe we'll need to rework those sections, or perhaps the text could be shorter. Let me know what you think.

**Comment by iskerrett** [comment] 2023-07-19 17:53
I think it would be useful to rework this page. Some comments on the existing layout:
- I agree there is a lot of text but it can be formatted better. We can increase font size, left justify and maybe even try two columns.  I can also delete some text but I'd like to see some rework to see if different formats make it look better.
- There is too much space between each sections. 
- The Node-RED and Open Source section are far too big.  You could reduce the size of the logos and maybe add them beside the text?  Not sure about this but it shouldn't take up so much space. 
- The break between investors and Working at FF isn't consistent with the rest of the page.

**Comment by Yndira-FlowForge** [comment] 2023-07-21 10:58
Hi, I've worked in two versions.
V1:

![About Us_Dark](https://github.com/flowforge/website/assets/129537638/68ab0d49-2469-4fe2-a0fe-a136de5d2755)

But the second section doesn't have a title, and with such a clear division from the first section, it seems like they are two completely separate things... Which I'm not sure is entirely accurate.

So, I thought about this version, where there are still two sections but less differentiated.
V2:

![About Us_Light](https://github.com/flowforge/website/assets/129537638/69220c3e-1af9-43e5-8c28-ca3fa484fca7)

What do you think?

**Comment by iskerrett** [comment] 2023-07-21 12:44
I like the second one. The first section seems to need some type of graphic? What about putting the FlowForge logo there? We could also add some pictures of team members?

**Comment by Yndira-FlowForge** [comment] 2023-07-24 18:54
Hi @iskerrett  
Here's a new version with the discussed image in place and the corporate values a bit smaller:


![Image](https://github.com/flowforge/website/assets/129537638/98223614-422a-4b60-9bd8-2600556b0673)

**Comment by iskerrett** [comment] 2023-07-24 19:02
I like it!!  Let's ship it.

**Closed** 2023-07-28 13:55 UTC
Labels: task
